### ISSUE TITLE
New book request A Common-Sense Guide to Data Structures and Algorithms in JavaScript, Volume 1

### ISSUE THREAD

**Issue by aruprakshit** [GauravWalia19/Free-Algorithms-Books#129]
Book Name
A Common-Sense Guide to Data Structures and Algorithms in JavaScript, Volume 1

Programming Language
JavaScript

Book Download Link
http://

**Comment by nagesh-c** [comment]
Looks like it is already there 
https://github.com/GauravWalia19/Free-Algorithms-Books/blob/main/Library/src/JAVASCRIPT/A-Common-Sense-Guide-to-Data-Structures-and-Algorithms-Level-Up-Your-Core-Programming-Skills.pdf
